### ISSUE TITLE
a bug when i try to run preprocess.py

### ISSUE THREAD

**Issue by linzhk** [ZhihongShao/Planning-based-Hierarchical-Variational-Model#1]
`Traceback (most recent call last):
  File "preprocess.py", line 10, in <module>
    pickle.dump(Vocabulary.Vocabulary(), open(config.vocab_file, "wb"))
  File "/home/lzk/Planning-based-Hierarchical-Variational-Model/Vocabulary.py", line 33, in __init__
    with open(self.config.wordvec_file) as file:
FileNotFoundError: [Errno 2] No such file or directory: './data/processed/wordvec.txt'
`
how to fix it?

**Comment by linzhk** [comment]
I found that if you run preprocess.py separately the problem will be solved

`config = Config.config
    #subprocess.run("python word2vec.py --corpus ./data/processed/corpus.txt --result\_dir ./data/processed/ --min\_count 1".split(), stdout=PIPE, stderr=PIPE)
    pickle.dump(Vocabulary.Vocabulary(), open(config.vocab_file, "wb"))`

**Comment by rxc205** [comment]
> I found that if you run preprocess.py separately the problem will be solved
> 
> `config = Config.config #subprocess.run("python word2vec.py --corpus ./data/processed/corpus.txt --result\_dir ./data/processed/ --min\_count 1".split(), stdout=PIPE, stderr=PIPE) pickle.dump(Vocabulary.Vocabulary(), open(config.vocab_file, "wb"))`

what do you mean? you mean  1.subprocess.run(...)    2.pickle.dump()  separately?

**Comment by ZhihongShao** [comment]
I have updated my code to solve this issue.
